/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistrictsRouteImport } from './routes/districts'
import { Route as DistrictsDistrictSlugRouteImport } from './routes/districts.$districtSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsRoute = DistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsDistrictSlugRoute = DistrictsDistrictSlugRouteImport.update({
  id: '/$districtSlug',
  path: '/$districtSlug',
  getParentRoute: () => DistrictsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRouteWithChildren
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/districts' | '/districts/$districtSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/districts' | '/districts/$districtSlug'
  id: '__root__' | '/' | '/districts' | '/districts/$districtSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictsRoute: typeof DistrictsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts': {
      id: '/districts'
      path: '/districts'
      fullPath: '/districts'
      preLoaderRoute: typeof DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$districtSlug': {
      id: '/districts/$districtSlug'
      path: '/$districtSlug'
      fullPath: '/districts/$districtSlug'
      preLoaderRoute: typeof DistrictsDistrictSlugRouteImport
      parentRoute: typeof DistrictsRoute
    }
  }
}

interface DistrictsRouteChildren {
  DistrictsDistrictSlugRoute: typeof DistrictsDistrictSlugRoute
}

const DistrictsRouteChildren: DistrictsRouteChildren = {
  DistrictsDistrictSlugRoute: DistrictsDistrictSlugRoute,
}

const DistrictsRouteWithChildren = DistrictsRoute._addFileChildren(
  DistrictsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictsRoute: DistrictsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
