/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsPlaceSlugRouteImport } from './routes/destinations.$placeSlug'
import { Route as DistrictsIndexRouteImport } from './routes/districts.index'
import { Route as DistrictsDistrictSlugRouteImport } from './routes/districts.$districtSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsPlaceSlugRoute = DestinationsPlaceSlugRouteImport.update({
  id: '/destinations/$placeSlug',
  path: '/destinations/$placeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsIndexRoute = DistrictsIndexRouteImport.update({
  id: '/districts/',
  path: '/districts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsDistrictSlugRoute = DistrictsDistrictSlugRouteImport.update({
  id: '/districts/$districtSlug',
  path: '/districts/$districtSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations/$placeSlug': typeof DestinationsPlaceSlugRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations/$placeSlug': typeof DestinationsPlaceSlugRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/districts': typeof DistrictsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations/$placeSlug': typeof DestinationsPlaceSlugRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/districts/': typeof DistrictsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations/$placeSlug'
    | '/districts/$districtSlug'
    | '/destinations/'
    | '/districts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/destinations/$placeSlug'
    | '/districts/$districtSlug'
    | '/destinations'
    | '/districts'
  id:
    | '__root__'
    | '/'
    | '/destinations/$placeSlug'
    | '/districts/$districtSlug'
    | '/destinations/'
    | '/districts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsPlaceSlugRoute: typeof DestinationsPlaceSlugRoute
  DistrictsDistrictSlugRoute: typeof DistrictsDistrictSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  DistrictsIndexRoute: typeof DistrictsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$placeSlug': {
      id: '/destinations/$placeSlug'
      path: '/destinations/$placeSlug'
      fullPath: '/destinations/$placeSlug'
      preLoaderRoute: typeof DestinationsPlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/': {
      id: '/districts/'
      path: '/districts'
      fullPath: '/districts/'
      preLoaderRoute: typeof DistrictsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$districtSlug': {
      id: '/districts/$districtSlug'
      path: '/districts/$districtSlug'
      fullPath: '/districts/$districtSlug'
      preLoaderRoute: typeof DistrictsDistrictSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsPlaceSlugRoute: DestinationsPlaceSlugRoute,
  DistrictsDistrictSlugRoute: DistrictsDistrictSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  DistrictsIndexRoute: DistrictsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
